### ISSUE TITLE
Adding a rule without UID to the RuleRegistry fails with NPE

### ISSUE THREAD

**Issue by kaikreuzer** [marinmitev/smarthome#134]
Calling ruleRegistry.add(rule) for a rule without UID results in

```
Caused by: java.lang.NullPointerException: null
    at org.mapdb.BTreeMap.get(BTreeMap.java:595)
    at org.mapdb.BTreeMap.get(BTreeMap.java:591)
    at org.eclipse.smarthome.storage.mapdb.MapDbStorage.get(MapDbStorage.java:76)
    at org.eclipse.smarthome.core.common.registry.AbstractManagedProvider.add(AbstractManagedProvider.java:55)
    at org.eclipse.smarthome.core.common.registry.AbstractRegistry.add(AbstractRegistry.java:112)
    at org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl.add(RuleRegistryImpl.java:76)
    at org.eclipse.smarthome.automation.core.internal.RuleRegistryImpl.add(RuleRegistryImpl.java:1)
```

The UID only seems to be created for the RuntimeRule, but it is not set in the Rule object itself before passing it to super.add(rule).

**Comment by kaikreuzer** [comment]
fixed through https://github.com/marinmitev/smarthome/pull/136
