### ISSUE TITLE
Synchronize ResourceBundleProviders

### ISSUE THREAD

**Issue by BenediktNiehues** [marinmitev/smarthome#83]
The IntegrationTest "assert that a rule created from a template is executed as expected" does sometimes not work because there seems to be a problem with the ResourceBundleProviders: while parsing the templates, they are validated, but the modules referenced in the template are not yet parsed. This causes that the template never will be loaded. There has to be a mechanism which tries to import failed templates again if moduleTypes are added.

Additionally here is the stacktrace:

```
13:29:19.753 [Automation Provider Processing Queue] ERROR o.e.s.a.p.json.TemplateJSONParser - [Template  UID : SimpleTestTemplate] Failed to validate connections of RuleTemplate with UID "SimpleTestTemplate"! Condition Type "ItemStateConditionX" does not exist!
java.lang.IllegalArgumentException: Condition Type "ItemStateConditionX" does not exist!
    at org.eclipse.smarthome.automation.core.util.ConnectionValidator.validateConditionConnections(ConnectionValidator.java:169) ~[org.eclipse.smarthome.automation.core/:na]
    at org.eclipse.smarthome.automation.core.util.ConnectionValidator.validateConnections(ConnectionValidator.java:51) ~[org.eclipse.smarthome.automation.core/:na]
    at org.eclipse.smarthome.automation.core.provider.TemplateResourceBundleProvider.importData(TemplateResourceBundleProvider.java:244) ~[org.eclipse.smarthome.automation.providers/:na]
    at org.eclipse.smarthome.automation.core.provider.AbstractResourceBundleProvider.processAutomationProvider(AbstractResourceBundleProvider.java:317) [org.eclipse.smarthome.automation.providers/:na]
    at org.eclipse.smarthome.automation.core.provider.AutomationResourceBundlesEventQueue.processBundleChanged(AutomationResourceBundlesEventQueue.java:316) [org.eclipse.smarthome.automation.providers/:na]
    at org.eclipse.smarthome.automation.core.provider.AutomationResourceBundlesEventQueue.run(AutomationResourceBundlesEventQueue.java:144) [org.eclipse.smarthome.automation.providers/:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_55]
```

**Comment by hristostanchev** [comment]
It is ready. Benedikt needs to verify that it is OK.
